services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  datadog-agent:
    image: registry.datadoghq.com/agent:7
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-us5.datadoghq.com}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: 'true'
      DD_APM_ENABLED: 'true'
      DD_APM_NON_LOCAL_TRAFFIC: 'true'
      DD_APM_RECEIVER_SOCKET: /var/run/datadog/apm.socket
      DD_DOGSTATSD_SOCKET: /var/run/datadog/dsd.socket
      DD_LOGS_ENABLED: 'true'
    ports:
      - '8126:8126'
      - '8125:8125/udp'
    volumes:
      - /var/run/datadog:/var/run/datadog
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

volumes:
  postgres_data:
